import React, { useState } from 'react';
import { useAppStore } from '../../stores/appStore';
import { useMeshStore } from '../../stores/meshStore';
import './RightSidebar.css';

/**
 * Right sidebar with view controls, versions, and export options
 */
function RightSidebar() {
  const { 
    viewMode, 
    setViewMode, 
    showSkullOverlay, 
    setShowSkullOverlay,
    showLandmarks,
    setShowLandmarks,
    setCameraView,
    openModal,
    meshControls,
    addNotification
  } = useAppStore();
  
  const { versions, currentVersionId, saveVersion, loadVersion, exportGeometry } = useMeshStore();
  
  const [expandedSections, setExpandedSections] = useState({
    view: true,
    camera: true,
    versions: true,
    export: false
  });

  const [versionName, setVersionName] = useState('');

  const toggleSection = (section) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const handleSaveVersion = () => {
    if (versionName.trim()) {
      saveVersion(versionName.trim());
      setVersionName('');
      addNotification({ type: 'success', title: 'Version Saved', message: `Saved version: ${versionName.trim()}` });
    }
  };

  const handleExportGLTF = () => {
    if (meshControls?.exportMesh) {
      meshControls.exportMesh('gltf');
    } else {
      addNotification({ type: 'warning', title: 'Export', message: 'Mesh not ready for export' });
    }
  };

  const handleExportGLB = () => {
    if (meshControls?.exportMesh) {
      meshControls.exportMesh('glb');
    } else {
      addNotification({ type: 'warning', title: 'Export', message: 'Mesh not ready for export' });
    }
  };

  const handleExportOBJ = () => {
    // OBJ export - simplified version
    const geometry = exportGeometry();
    if (geometry) {
      let obj = '# Facial Reconstruction Export\n';
      obj += '# Generated by REface ID\n\n';
      
      // Add vertices
      for (let i = 0; i < geometry.vertices.length; i += 3) {
        obj += `v ${geometry.vertices[i]} ${geometry.vertices[i+1]} ${geometry.vertices[i+2]}\n`;
      }
      
      // Add faces (assuming triangles, 1-indexed)
      const numVertices = geometry.vertices.length / 3;
      for (let i = 0; i < numVertices; i += 3) {
        obj += `f ${i+1} ${i+2} ${i+3}\n`;
      }
      
      const blob = new Blob([obj], { type: 'text/plain' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = 'face_reconstruction.obj';
      link.click();
      addNotification({ type: 'success', title: 'Export Complete', message: 'Exported as OBJ' });
    } else {
      addNotification({ type: 'warning', title: 'Export', message: 'No geometry to export' });
    }
  };

  const handleRenderImage = () => {
    if (meshControls?.captureScreenshot) {
      meshControls.captureScreenshot();
    } else {
      addNotification({ type: 'warning', title: 'Screenshot', message: 'Renderer not ready' });
    }
  };

  const cameraViews = [
    { id: 'front', name: 'Front', icon: '◯' },
    { id: 'left', name: 'Left', icon: '◐' },
    { id: 'right', name: 'Right', icon: '◑' },
    { id: 'top', name: 'Top', icon: '◓' },
    { id: 'back', name: 'Back', icon: '●' }
  ];

  return (
    <div className="right-sidebar">
      {/* View Mode Section */}
      <div className="sidebar-section">
        <div 
          className="sidebar-section-header"
          onClick={() => toggleSection('view')}
        >
          <span className="sidebar-section-title">View Mode</span>
          <svg 
            className={`sidebar-section-toggle ${expandedSections.view ? 'expanded' : ''}`}
            width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
          >
            <polyline points="6 9 12 15 18 9"></polyline>
          </svg>
        </div>
        
        {expandedSections.view && (
          <div className="sidebar-section-content expanded">
            <div className="view-mode-buttons">
              <button
                className={`view-mode-btn ${viewMode === 'shaded' ? 'active' : ''}`}
                onClick={() => setViewMode('shaded')}
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                  <circle cx="12" cy="12" r="10"/>
                </svg>
                Shaded
              </button>
              <button
                className={`view-mode-btn ${viewMode === 'wireframe' ? 'active' : ''}`}
                onClick={() => setViewMode('wireframe')}
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10"/>
                  <path d="M12 2v20M2 12h20"/>
                </svg>
                Wireframe
              </button>
              <button
                className={`view-mode-btn ${viewMode === 'both' ? 'active' : ''}`}
                onClick={() => setViewMode('both')}
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="12" cy="12" r="10" fill="currentColor" fillOpacity="0.3"/>
                  <path d="M12 2v20M2 12h20"/>
                </svg>
                Both
              </button>
            </div>

            <div className="view-options">
              <label className="view-option">
                <input
                  type="checkbox"
                  checked={showSkullOverlay}
                  onChange={(e) => setShowSkullOverlay(e.target.checked)}
                />
                <span className="checkbox-custom"></span>
                <span>Show Skull Overlay</span>
              </label>
              
              <label className="view-option">
                <input
                  type="checkbox"
                  checked={showLandmarks}
                  onChange={(e) => setShowLandmarks(e.target.checked)}
                />
                <span className="checkbox-custom"></span>
                <span>Show Landmarks</span>
              </label>
            </div>
          </div>
        )}
      </div>

      {/* Camera Views Section */}
      <div className="sidebar-section">
        <div 
          className="sidebar-section-header"
          onClick={() => toggleSection('camera')}
        >
          <span className="sidebar-section-title">Camera Views</span>
          <svg 
            className={`sidebar-section-toggle ${expandedSections.camera ? 'expanded' : ''}`}
            width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
          >
            <polyline points="6 9 12 15 18 9"></polyline>
          </svg>
        </div>
        
        {expandedSections.camera && (
          <div className="sidebar-section-content expanded">
            <div className="camera-view-grid">
              {cameraViews.map(view => (
                <button
                  key={view.id}
                  className="camera-view-btn"
                  onClick={() => setCameraView(view.id)}
                >
                  <span className="camera-icon">{view.icon}</span>
                  <span>{view.name}</span>
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Version History Section */}
      <div className="sidebar-section">
        <div 
          className="sidebar-section-header"
          onClick={() => toggleSection('versions')}
        >
          <span className="sidebar-section-title">Version History</span>
          <svg 
            className={`sidebar-section-toggle ${expandedSections.versions ? 'expanded' : ''}`}
            width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
          >
            <polyline points="6 9 12 15 18 9"></polyline>
          </svg>
        </div>
        
        {expandedSections.versions && (
          <div className="sidebar-section-content expanded">
            <div className="version-save">
              <input
                type="text"
                className="input version-name-input"
                placeholder="Version name..."
                value={versionName}
                onChange={(e) => setVersionName(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSaveVersion()}
              />
              <button 
                className="btn btn-primary btn-sm"
                onClick={handleSaveVersion}
                disabled={!versionName.trim()}
              >
                Save
              </button>
            </div>

            <div className="version-list">
              {versions.length === 0 ? (
                <div className="version-empty">
                  <p>No saved versions</p>
                  <p className="text-muted text-sm">Save versions to track your progress</p>
                </div>
              ) : (
                versions.map(version => (
                  <div 
                    key={version.id}
                    className={`version-item ${currentVersionId === version.id ? 'active' : ''}`}
                    onClick={() => loadVersion(version.id)}
                  >
                    <div className="version-info">
                      <span className="version-name">{version.name}</span>
                      <span className="version-date">
                        {new Date(version.createdAt).toLocaleString()}
                      </span>
                    </div>
                    {currentVersionId === version.id && (
                      <span className="version-current">Current</span>
                    )}
                  </div>
                ))
              )}
            </div>
          </div>
        )}
      </div>

      {/* Export Section */}
      <div className="sidebar-section">
        <div 
          className="sidebar-section-header"
          onClick={() => toggleSection('export')}
        >
          <span className="sidebar-section-title">Export</span>
          <svg 
            className={`sidebar-section-toggle ${expandedSections.export ? 'expanded' : ''}`}
            width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
          >
            <polyline points="6 9 12 15 18 9"></polyline>
          </svg>
        </div>
        
        {expandedSections.export && (
          <div className="sidebar-section-content expanded">
            <div className="export-buttons">
              <button className="btn btn-secondary export-btn" onClick={handleExportGLTF}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                  <polyline points="7 10 12 15 17 10"></polyline>
                  <line x1="12" y1="15" x2="12" y2="3"></line>
                </svg>
                Export GLTF
              </button>
              
              <button className="btn btn-secondary export-btn" onClick={handleExportGLB}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                  <polyline points="7 10 12 15 17 10"></polyline>
                  <line x1="12" y1="15" x2="12" y2="3"></line>
                </svg>
                Export GLB
              </button>
              
              <button className="btn btn-secondary export-btn" onClick={handleExportOBJ}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                  <polyline points="7 10 12 15 17 10"></polyline>
                  <line x1="12" y1="15" x2="12" y2="3"></line>
                </svg>
                Export OBJ
              </button>
              
              <div className="export-divider"></div>
              
              <button className="btn btn-primary export-btn" onClick={handleRenderImage}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
                  <circle cx="8.5" cy="8.5" r="1.5"></circle>
                  <polyline points="21 15 16 10 5 21"></polyline>
                </svg>
                Render Image
              </button>
              
              <button className="btn btn-secondary export-btn" onClick={() => openModal('comparison')}>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="2" y="3" width="20" height="14" rx="2" ry="2"></rect>
                  <line x1="8" y1="21" x2="16" y2="21"></line>
                  <line x1="12" y1="17" x2="12" y2="21"></line>
                  <line x1="12" y1="3" x2="12" y2="17"></line>
                </svg>
                Side-by-Side Compare
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default RightSidebar;
